---
name: Polycom-Contact-Directory
version: 0.01
author: ["Zachary Blair"]
abstract: 'Parse local contact directory files for Polycom VoIP phones'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0
  Test::More: 0
  List::MoreUtils 0
  XML::Simple: 0
  perl: 5.6.2
provides:
  Polycom-Contact-Directory:
    file: lib/Polycom/Contact/Directory.pm
    version: 0.01
  Polycom-Contact:
    file: lib/Polycom/Contact.pm
    version: 0.01
keywords:
	- Polycom
	- VoIP
	- Contact
	- Directory
	- SoundPoint
