---
name: Polycom-Contact-Directory
version: 0.03
author: ["Zachary Blair <zachary.blair@polycom.com>"]
abstract: 'Parse local contact directory files for Polycom VoIP phones'
license: perl
distribution_type: module
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0
  Encode: 0
  IO::File: 0
  List::MoreUtils: 0
  Test::More: 0
  perl: 5.8
provides:
  Polycom::Contact::Directory:
    file: lib/Polycom/Contact/Directory.pm
    version: 0.03
  Polycom::Contact:
    file: lib/Polycom/Contact.pm
    version: 0.03
keywords:
  - Polycom
  - VoIP
  - Contact
  - Directory
  - SoundPoint
  - VVX
